# Generated by Django 5.1 on 2024-08-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(upload_to='postagens/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Interesse',
            new_name='CursoRealizado',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
